# Useful Pandas Commands Demo

<sup>This notebook is a part of Natural Language Processing class at the University of Ljubljana, Faculty for computer and information science. Please contact [ales.zagar@fri.uni-lj.si](mailto:ales.zagar@fri.uni-lj.si) for any comments.</sup>

This notebook showcases a practical set of pandas commands on a small toy dataset with 10 samples. The goal is to provide a quick reference for the commands that are most useful in day-to-day data exploration and wrangling.

## Import pandas and create toy data

In [22]:
import pandas as pd

data = {
    "student": ["Ana", "Boris", "Cvetka", "David", "Eva", "Filip", "Gaja", "Hana", "Ivan", "Jana"],
    "language": ["Python", "R", "Python", "Java", "Python", "R", "Python", "Java", "Python", "R"],
    "score": [88, 76, 91, 65, 84, None, 95, 72, 89, 78],
    "hours_studied": [12, 8, 15, 6, 10, 7, 16, 9, 13, 11],
    "passed": [True, True, True, False, True, True, True, False, True, True]
}

df = pd.DataFrame(data)
df

  student language  score  hours_studied  passed
0     Ana   Python   88.0             12    True
1   Boris        R   76.0              8    True
2  Cvetka   Python   91.0             15    True
3   David     Java   65.0              6   False
4     Eva   Python   84.0             10    True
5   Filip        R    NaN              7    True
6    Gaja   Python   95.0             16    True
7    Hana     Java   72.0              9   False
8    Ivan   Python   89.0             13    True
9    Jana        R   78.0             11    True

## Inspect the dataframe

Useful commands: `head()`, `tail()`, `shape`, `columns`, `info()`, `describe()`.

In [23]:
print("Shape:", df.shape)
print("Columns:", list(df.columns))

df.head(3)

Shape: (10, 5)
Columns: ['student', 'language', 'score', 'hours_studied', 'passed']

  student language  score  hours_studied  passed
0     Ana   Python   88.0             12    True
1   Boris        R   76.0              8    True
2  Cvetka   Python   91.0             15    True

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student        10 non-null     object
 1   language       10 non-null     object
 2   score          9 non-null      float64
 3   hours_studied  10 non-null     int64
 4   passed         10 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 458.0+ bytes

In [25]:
df.describe(include="all")

       student language      score  hours_studied passed
count       10       10   9.000000         10.000     10
unique      10        3        NaN            NaN      2
top        Ana   Python        NaN            NaN   True
freq         1        5        NaN            NaN      8
mean       NaN      NaN  82.000000         10.700    NaN
std        NaN      NaN   9.874209          3.335    NaN
min        NaN      NaN  65.000000          6.000    NaN
25%        NaN      NaN  76.000000          8.250    NaN
50%        NaN      NaN  84.000000         10.500    NaN
75%        NaN      NaN  89.000000         12.750    NaN
max        NaN      NaN  95.000000         16.000    NaN

## Select columns and filter rows

Useful commands: column selection, boolean filtering, `loc`, `iloc`, `query()`.

In [26]:
# Select two columns
df[["student", "score"]]

  student  score
0     Ana   88.0
1   Boris   76.0
2  Cvetka   91.0
3   David   65.0
4     Eva   84.0
5   Filip    NaN
6    Gaja   95.0
7    Hana   72.0
8    Ivan   89.0
9    Jana   78.0

In [27]:
# Students who studied more than 10 hours and passed
df[(df["hours_studied"] > 10) & (df["passed"])]

  student language  score  hours_studied  passed
0     Ana   Python   88.0             12    True
2  Cvetka   Python   91.0             15    True
6    Gaja   Python   95.0             16    True
8    Ivan   Python   89.0             13    True
9    Jana        R   78.0             11    True

In [29]:
# loc uses labels, iloc uses integer positions
df.loc[df["language"] == "Python", ["student", "language", "score"]]

  student language  score
0     Ana   Python   88.0
2  Cvetka   Python   91.0
4     Eva   Python   84.0
6    Gaja   Python   95.0
8    Ivan   Python   89.0

In [28]:
df.iloc[:4, :3]

  student language  score
0     Ana   Python   88.0
1   Boris        R   76.0
2  Cvetka   Python   91.0
3   David     Java   65.0

## Create and modify columns

Useful commands: `assign()`, arithmetic on columns, `map()`, `replace()`.

In [30]:
df2 = df.assign(
    score_filled=df["score"].fillna(df["score"].mean()),
    score_per_hour=(df["score"].fillna(df["score"].mean()) / df["hours_studied"]).round(2),
    level=df["score"].map(lambda x: "missing" if pd.isna(x) else ("high" if x >= 85 else "medium" if x >= 75 else "low"))
)

df2

,student,language,score,hours_studied,passed,score_filled,score_per_hour,level
0,Ana,Python,88.0,12,True,88.0,7.33,high
1,Boris,R,76.0,8,True,76.0,9.50,medium
2,Cvetka,Python,91.0,15,True,91.0,6.07,high
3,David,Java,65.0,6,False,65.0,10.83,low
4,Eva,Python,84.0,10,True,84.0,8.40,medium
5,Filip,R,NaN,7,True,82.0,11.71,missing
6,Gaja,Python,95.0,16,True,95.0,5.94,high
7,Hana,Java,72.0,9,False,72.0,8.00,low
8,Ivan,Python,89.0,13,True,89.0,6.85,high
9,Jana,R,78.0,11,True,78.0,7.09,medium

## Sort, count values, and find missing data

Useful commands: `sort_values()`, `value_counts()`, `isna()`, `fillna()`.

In [31]:
df.sort_values(by="score", ascending=False, na_position="last")

  student language  score  hours_studied  passed
6    Gaja   Python   95.0             16    True
2  Cvetka   Python   91.0             15    True
8    Ivan   Python   89.0             13    True
0     Ana   Python   88.0             12    True
4     Eva   Python   84.0             10    True
9    Jana        R   78.0             11    True
1   Boris        R   76.0              8    True
7    Hana     Java   72.0              9   False
3   David     Java   65.0              6   False
5   Filip        R    NaN              7    True

In [32]:
df["language"].value_counts()

language
Python    5
R         3
Java      2
Name: count, dtype: int64

In [33]:
print("Any missing values?", df.isna().any().any())
df.isna().sum()

Any missing values? True

student          0
language         0
score            1
hours_studied    0
passed           0
dtype: int64

## Group by category and aggregate

Useful commands: `groupby()`, `agg()`, `mean()`, `count()`.

In [39]:
df.groupby("language").agg(
    average_score=("score", "mean"),
    average_hours=("hours_studied", "mean"),
    students=("student", "count")
).round(2)

          average_score  average_hours  students
language
Java               68.5           7.50         2
Python             89.4          13.20         5
R                  77.0           8.67         3

In [38]:
df['score'].mean()
df['score'].median()

np.float64(84.0)

## Merge with another dataframe

Useful command: `merge()`.

In [42]:
language_info = pd.DataFrame({
    "language": ["Python", "R", "Java"],
    "type": ["scripting", "statistical", "compiled"]
})
language_info

  language         type
0   Python    scripting
1        R  statistical
2     Java     compiled

In [43]:
df

  student language  score  hours_studied  passed
0     Ana   Python   88.0             12    True
1   Boris        R   76.0              8    True
2  Cvetka   Python   91.0             15    True
3   David     Java   65.0              6   False
4     Eva   Python   84.0             10    True
5   Filip        R    NaN              7    True
6    Gaja   Python   95.0             16    True
7    Hana     Java   72.0              9   False
8    Ivan   Python   89.0             13    True
9    Jana        R   78.0             11    True

In [44]:
df.merge(language_info, on="language", how="left")

  student language  score  hours_studied  passed         type
0     Ana   Python   88.0             12    True    scripting
1   Boris        R   76.0              8    True  statistical
2  Cvetka   Python   91.0             15    True    scripting
3   David     Java   65.0              6   False     compiled
4     Eva   Python   84.0             10    True    scripting
5   Filip        R    NaN              7    True  statistical
6    Gaja   Python   95.0             16    True    scripting
7    Hana     Java   72.0              9   False     compiled
8    Ivan   Python   89.0             13    True    scripting
9    Jana        R   78.0             11    True  statistical

## Drop duplicates and rename columns

Useful commands: `drop_duplicates()`, `rename()`.

In [45]:
df[["language"]].drop_duplicates()

  language
0   Python
1        R
3     Java

In [46]:
df[["language"]]

  language
0   Python
1        R
2   Python
3     Java
4   Python
5        R
6   Python
7     Java
8   Python
9        R

In [47]:
df.rename(columns={"hours_studied": "hours", "passed": "exam_passed"})

  student language  score  hours  exam_passed
0     Ana   Python   88.0     12         True
1   Boris        R   76.0      8         True
2  Cvetka   Python   91.0     15         True
3   David     Java   65.0      6        False
4     Eva   Python   84.0     10         True
5   Filip        R    NaN      7         True
6    Gaja   Python   95.0     16         True
7    Hana     Java   72.0      9        False
8    Ivan   Python   89.0     13         True
9    Jana        R   78.0     11         True

## Summary

This notebook demonstrated a compact set of pandas operations that are commonly useful:

- Creating a dataframe
- Inspecting data
- Selecting and filtering
- Creating new columns
- Handling missing values
- Sorting and counting values
- Grouping and aggregating
- Building a pivot table
- Merging dataframes
- Renaming columns and removing duplicates